dependencies:
  - r-base=4.3.3

  # Bioconductor 
  - bioconductor-complexheatmap=2.18.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-iranges=2.36.0
  - bioconductor-biocgenerics=0.48.1

  # CRAN
  - r-caret=7.0_1
  - r-pROC=1.18.5
  - r-matrixstats=1.5.0
  - r-data.table=1.17.0
  - r-nmf=0.29.1
  - r-polychrome=1.5.1
  - r-ggplot2=3.5.1

  # Others
  - r-dplyr
  - r-lubridate
  - r-readxl
  - r-tidyr
  - r-stringr
  - r-forcats
  - r-purrr
  - r-here
  - r-rmarkdown
  - r-survival
  - r-survminer
  - r-ggpubr
  - r-gridextra
  - r-ggh4x
  - r-ggforce
  - r-reshape2
  - r-circlize
  - r-rcolorbrewer
  - r-lemon
  - r-jsonlite
  - r-png
  - r-magick
  - r-yaml